name: maintenance_app
description: It is an electronic store application and a request for maintenance of electrical appliances specific to the user.
publish_to: 'none'

version: 1.0.0+8

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.2.0
  flutter_localization: ^0.3.3
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.0
  flutter_screenutil: ^5.8.4
  connectivity_plus: ^4.0.0
  internet_connection_checker: ^1.0.0
  lottie: ^2.0.0
  font_awesome_flutter: ^10.7.0
  flutter_rating_bar: ^4.0.1
  dropdown_search: ^5.0.6
  qr_flutter: ^4.1.0
  url_launcher: ^6.1.12
  csc_picker: ^0.2.7
  image_picker: ^1.0.2
  google_maps_flutter: ^2.10.0
  share_plus: ^10.1.3
  geolocator: ^13.0.2
  permission_handler: ^11.3.1
  carousel_slider: ^5.1.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  cached_network_image: ^3.4.1
  http: ^1.1.0
  win32: ^5.9.0
  get_it: ^8.0.1
  flutter_plugin_android_lifecycle: ^2.0.23
  flutter_credit_card: ^3.0.2
  firebase_core: ^3.15.2
  firebase_messaging: ^15.1.6
  flutter_local_notifications: ^19.3.1
  device_info_plus: ^11.2.0
  package_info_plus: ^8.1.2
  webview_flutter: ^4.10.0
  xml: ^6.5.0
  mobile_scanner: ^6.0.7
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/

  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai/Almarai-Bold.ttf
        - asset: assets/fonts/Almarai/Almarai-ExtraBold.ttf
        - asset: assets/fonts/Almarai/Almarai-Light.ttf
        - asset: assets/fonts/Almarai/Almarai-Regular.ttf
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal-Black.ttf
        - asset: assets/fonts/Tajawal/Tajawal-Bold.ttf
        - asset: assets/fonts/Tajawal/Tajawal-ExtraBold.ttf
        - asset: assets/fonts/Tajawal/Tajawal-ExtraLight.ttf
        - asset: assets/fonts/Tajawal/Tajawal-Light.ttf
        - asset: assets/fonts/Tajawal/Tajawal-Medium.ttf
        - asset: assets/fonts/Tajawal/Tajawal-Regular.ttf