// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM_uMt9L0-9TI5_txKhYmYYjTi430EtKY',
    appId: '1:789629070506:web:ca300277485ee26a3eb4d3',
    messagingSenderId: '789629070506',
    projectId: 'maintenanceapp-334b0',
    authDomain: 'maintenanceapp-334b0.firebaseapp.com',
    storageBucket: 'maintenanceapp-334b0.firebasestorage.app',
    measurementId: 'G-XFLNC9WLDM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkbmZBrhTnbPBHcLGs7rzDRyZKn3aTK1Y',
    appId: '1:789629070506:android:2c4538b5a643add43eb4d3',
    messagingSenderId: '789629070506',
    projectId: 'maintenanceapp-334b0',
    storageBucket: 'maintenanceapp-334b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmiwZ6I9P23trdBuNqKB_c_YL82e3U1ZQ',
    appId: '1:789629070506:ios:2f2c118bbfe0a2ba3eb4d3',
    messagingSenderId: '789629070506',
    projectId: 'maintenanceapp-334b0',
    storageBucket: 'maintenanceapp-334b0.firebasestorage.app',
    iosBundleId: 'com.example.maintenanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmiwZ6I9P23trdBuNqKB_c_YL82e3U1ZQ',
    appId: '1:789629070506:ios:2f2c118bbfe0a2ba3eb4d3',
    messagingSenderId: '789629070506',
    projectId: 'maintenanceapp-334b0',
    storageBucket: 'maintenanceapp-334b0.firebasestorage.app',
    iosBundleId: 'com.example.maintenanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCM_uMt9L0-9TI5_txKhYmYYjTi430EtKY',
    appId: '1:789629070506:web:a997d7de3045dc8f3eb4d3',
    messagingSenderId: '789629070506',
    projectId: 'maintenanceapp-334b0',
    authDomain: 'maintenanceapp-334b0.firebaseapp.com',
    storageBucket: 'maintenanceapp-334b0.firebasestorage.app',
    measurementId: 'G-G0WXH332JM',
  );
}
