// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4fcyGiDt6Y7avqh_NsBEwyARrq_fYhpE',
    appId: '1:536326779179:web:ea35e613b4673393fa956e',
    messagingSenderId: '536326779179',
    projectId: 'maintenanceapp-98abd',
    authDomain: 'maintenanceapp-98abd.firebaseapp.com',
    storageBucket: 'maintenanceapp-98abd.firebasestorage.app',
    measurementId: 'G-3LCVLEHJCJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC27o8KluDir8XUnpkOMUEBvazbOM-TtWI',
    appId: '1:536326779179:android:81f93144071c5640fa956e',
    messagingSenderId: '536326779179',
    projectId: 'maintenanceapp-98abd',
    storageBucket: 'maintenanceapp-98abd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_jyzgsn8FIkbiQIlELrUG5gqUKRoH-Is',
    appId: '1:536326779179:ios:f5ab7e428c1e10f4fa956e',
    messagingSenderId: '536326779179',
    projectId: 'maintenanceapp-98abd',
    storageBucket: 'maintenanceapp-98abd.firebasestorage.app',
    iosBundleId: 'com.example.maintenanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_jyzgsn8FIkbiQIlELrUG5gqUKRoH-Is',
    appId: '1:536326779179:ios:f5ab7e428c1e10f4fa956e',
    messagingSenderId: '536326779179',
    projectId: 'maintenanceapp-98abd',
    storageBucket: 'maintenanceapp-98abd.firebasestorage.app',
    iosBundleId: 'com.example.maintenanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4fcyGiDt6Y7avqh_NsBEwyARrq_fYhpE',
    appId: '1:536326779179:web:517cd0feb536faebfa956e',
    messagingSenderId: '536326779179',
    projectId: 'maintenanceapp-98abd',
    authDomain: 'maintenanceapp-98abd.firebaseapp.com',
    storageBucket: 'maintenanceapp-98abd.firebasestorage.app',
    measurementId: 'G-KS9B0EYZSQ',
  );
}
